Repository Ensembl/ensembl-biomart, pull requests merged in 2019-05, with the labels that each got.

#48 The Variation team doesn't re-generate the MTMP_variation_set_variati…
  modules/Bio/EnsEMBL/BioMart/CreateMTMPVariation.pm
  modules/Bio/EnsEMBL/EGPipeline/PipeConfig/VariationMart_conf.pm
  modules/Bio/EnsEMBL/EGPipeline/PipeConfig/VariationMart_eg_conf.pm
  modules/Bio/EnsEMBL/EGPipeline/PipeConfig/VariationMart_ensembl_conf.pm
  modules/Bio/EnsEMBL/EGPipeline/VariationMart/Base.pm
  modules/Bio/EnsEMBL/EGPipeline/VariationMart/CreateMTMPTables.pm
  modules/Bio/EnsEMBL/PipeConfig/BuildGeneMartMTMPTables_conf.pm
Labels: bau

#50 Changes to support recent Regulation schema changes, see here for det…
  martbuilder_xml/v97_xml/regulation_mart_97.xml
  scripts/templates/mirna_target_feature_template_template.xml
Labels: bau

#51 The variation team have moved the ancestral_allele column from the va…
  scripts/templates/variation_som_template_template.xml
  scripts/templates/variation_template_template.xml
  var_mart/tables/snp__variation__main/select.sql
  var_mart/tables/snp__variation_feature__main/select.sql
  var_mart/tables/snp_som__variation__main/select.sql
  var_mart/tables/snp_som__variation_feature__main/select.sql
Labels: bau

#49 Gene stable ID version and Transcript stable ID version attributes wi…
  scripts/templates/gene_template_template.xml
Labels: user request

#53 XML config for vertebrates genomic features mart
  martbuilder_xml/v97_xml/genomic_features_mart_97.xml
Labels: bau

#54 Release/97
  martbuilder_xml/v97_xml/genomic_features_mart_97.xml
  martbuilder_xml/v97_xml/metazoa_genomic_features_mart_44.xml
  martbuilder_xml/v97_xml/plants_genomic_features_mart_44.xml
  martbuilder_xml/v97_xml/protists_genomic_features_mart_44.xml
  martbuilder_xml/v97_xml/regulation_mart_97.xml
  modules/Bio/EnsEMBL/BioMart/CreateMTMPVariation.pm
  modules/Bio/EnsEMBL/EGPipeline/PipeConfig/VariationMartTidy_conf.pm
  modules/Bio/EnsEMBL/EGPipeline/PipeConfig/VariationMart_conf.pm
  modules/Bio/EnsEMBL/EGPipeline/PipeConfig/VariationMart_eg_conf.pm
  modules/Bio/EnsEMBL/EGPipeline/PipeConfig/VariationMart_ensembl_conf.pm
  modules/Bio/EnsEMBL/EGPipeline/VariationMart/Base.pm
  modules/Bio/EnsEMBL/EGPipeline/VariationMart/CreateMTMPTables.pm
  modules/Bio/EnsEMBL/PipeConfig/BuildGeneMartMTMPTables_conf.pm
  modules/Bio/EnsEMBL/PipeConfig/BuildMart_conf.pm
  modules/Bio/EnsEMBL/PipeConfig/BuildRegulationMart_conf.pm
  modules/Bio/EnsEMBL/PipeConfig/BuildSeqMart_conf.pm
  scripts/create_martbuilder_file.pl
  scripts/generate_meta_xrefs_exceptions.json
  scripts/pre_configuration_mart_healthcheck.pl
  scripts/templates/gene_template_template.xml
  scripts/templates/mirna_target_feature_template_template.xml
  scripts/templates/variation_som_template_template.xml
  scripts/templates/variation_template_template.xml
  var_mart/tables/snp__variation__main/select.sql
  var_mart/tables/snp__variation_feature__main/select.sql
  var_mart/tables/snp_som__variation__main/select.sql
  var_mart/tables/snp_som__variation_feature__main/select.sql
Labels: bau

#55 Forgot to remove v_m.ancestral_allele_2025 as this column doesn't exi…
  var_mart/tables/snp_som__variation_feature__main/select.sql
Labels: bug
