Repository Ensembl/ensembl-biomart, pull requests merged in 2019-12, with the labels that each got.

#82 Removed species from the excluded list to avoid getting confusing err…
  scripts/pre_configuration_mart_healthcheck.pl
Labels: enhancement

#80 Changing the way that dataset names are generated…
  modules/Bio/EnsEMBL/EGPipeline/VariationMart/CopyOrGenerate.pm
Labels: bug

#83 Release/99
  martbuilder_xml/v99_xml/ensembl_mart_99.xml
  martbuilder_xml/v99_xml/ensembl_template_99.xml
  martbuilder_xml/v99_xml/fungi_mart_46.xml
  martbuilder_xml/v99_xml/genomic_features_mart_99.xml
  martbuilder_xml/v99_xml/metazoa_genomic_features_mart_46.xml
  martbuilder_xml/v99_xml/metazoa_mart_46.xml
  martbuilder_xml/v99_xml/plants_genomic_features_mart_46.xml
  martbuilder_xml/v99_xml/plants_mart_46.xml
  martbuilder_xml/v99_xml/protists_mart_46.xml
  modules/Bio/EnsEMBL/EGPipeline/VariationMart/CopyOrGenerate.pm
  scripts/create_martbuilder_file.pl
  scripts/diffMart.sh
  scripts/pre_configuration_mart_healthcheck.pl
  scripts/soakTest.pl
Labels: bau
