Repository Ensembl/ensembl-biomart, pull requests merged in 2019-11, with the labels that each got.

#70 Added initial list of excluded species from bioMart
  scripts/exclude_vertebrates.ini
Labels: enhancement

#71 Fixed some broken species names
  scripts/exclude_vertebrates.ini
Labels: bug

#72 Feature/reduced species
  scripts/exclude_vertebrates.ini
Labels: bug

#73 Minor fix to test scripts
  scripts/compare_marts.pl
  scripts/test_mart.pl
Labels: bug

#74 Implement code to exclude a list of defined genomes in exclude_verteb…
  modules/Bio/EnsEMBL/BioMart/Mart.pm
  modules/Bio/EnsEMBL/BioMart/SequenceDatasetFactory.pm
  scripts/create_martbuilder_file.pl
Labels: bau

#75 Release/99
  martbuilder_xml/v99_xml/regulation_mart_99.xml
  modules/Bio/EnsEMBL/BioMart/Mart.pm
  modules/Bio/EnsEMBL/BioMart/MetaBuilder.pm
  modules/Bio/EnsEMBL/BioMart/SequenceDatasetFactory.pm
  scripts/compare_marts.pl
  scripts/create_martbuilder_file.pl
  scripts/exclude_vertebrates.ini
  scripts/pre_configuration_mart_healthcheck.pl
  scripts/templates/gene_template_template.xml
  scripts/test_mart.pl
Labels: bau

#76 Grch37 update
  scripts/create_martbuilder_file.pl
Labels: bau, enhancement

#77 Genomic features mart for release 99
  martbuilder_xml/v99_xml/genomic_features_mart_99.xml
  martbuilder_xml/v99_xml/metazoa_genomic_features_mart_46.xml
  martbuilder_xml/v99_xml/plants_genomic_features_mart_46.xml
Labels: bau

#78 Only report lost filters/attributes
  scripts/diffMart.sh
  scripts/soakTest.pl
Labels: enhancement

#79 Vert gene mart release 99
  martbuilder_xml/v99_xml/ensembl_mart_99.xml
Labels: bau

#81 Non-vert xml templates for release 99
  martbuilder_xml/v99_xml/ensembl_template_99.xml
  martbuilder_xml/v99_xml/fungi_mart_46.xml
  martbuilder_xml/v99_xml/metazoa_mart_46.xml
  martbuilder_xml/v99_xml/plants_mart_46.xml
  martbuilder_xml/v99_xml/protists_mart_46.xml
Labels: bau
