Repository Ensembl/ensembl-biomart, pull requests merged in 2021-03, with the labels that each got.

#135 Put regulation mart index creation on a separate flow
  modules/Bio/EnsEMBL/PipeConfig/BuildRegulationMart_conf.pm
Labels: enhancement

#137 Release back to master.
  martbuilder_templates_xml/ensembl_template.xml
  modules/Bio/EnsEMBL/BioMart/CheckExcludedSpecies.pm
  modules/Bio/EnsEMBL/BioMart/ConcatColumns.pm
  modules/Bio/EnsEMBL/BioMart/DatasetFactory.pm
  modules/Bio/EnsEMBL/EGPipeline/PipeConfig/VariationMart_conf.pm
  modules/Bio/EnsEMBL/EGPipeline/PipeConfig/VariationMart_ensembl_conf.pm
  modules/Bio/EnsEMBL/PipeConfig/BuildGeneMartMTMPTables_conf.pm
  modules/Bio/EnsEMBL/PipeConfig/BuildMart_conf.pm
  modules/Bio/EnsEMBL/PipeConfig/BuildRegulationMart_conf.pm
  modules/Bio/EnsEMBL/PipeConfig/BuildSeqMart_conf.pm
  scripts/templates/gene_template_template.xml
Labels: bau

#138 Added filters to Variation and Gen Marts
  .gitignore
  martbuilder_templates_xml/ensembl_template.xml
  scripts/templates/gene_template_template.xml
  scripts/templates/template_template.xml
  scripts/templates/variation_som_template_template.xml
  scripts/templates/variation_template_template.xml
Labels: bau

#139 Features/regulation remove motif features dataset
  modules/Bio/EnsEMBL/PipeConfig/BuildRegulationMart_conf.pm
Labels: bug, enhancement
